#############################################################################
# Makefile for building: qtserial
# Generated by qmake (2.01a) (Qt 4.5.2) on: ven. avr. 23 11:36:37 2010
# Project:  qtserial.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtserial.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_TTY_POSIX_ -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		win_qextserialport.cpp \
		serialtool.cpp \
		readserial.cpp \
		qextserialport.cpp \
		qextserialbase.cpp \
		posix_qextserialport.cpp moc_serialtool.cpp \
		moc_readserial.cpp
OBJECTS       = main.o \
		win_qextserialport.o \
		serialtool.o \
		readserial.o \
		qextserialport.o \
		qextserialbase.o \
		posix_qextserialport.o \
		moc_serialtool.o \
		moc_readserial.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtserial.pro
QMAKE_TARGET  = qtserial
DESTDIR       = 
TARGET        = qtserial

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_serialtool.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtserial.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtserial.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtserial.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtserial1.0.0 || $(MKDIR) .tmp/qtserial1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtserial1.0.0/ && $(COPY_FILE) --parents win_qextserialport.h ui_serialtool.h serialtool.h readserial.h qextserialport.h qextserialbase.h posix_qextserialport.h .tmp/qtserial1.0.0/ && $(COPY_FILE) --parents main.cpp win_qextserialport.cpp serialtool.cpp readserial.cpp qextserialport.cpp qextserialbase.cpp posix_qextserialport.cpp .tmp/qtserial1.0.0/ && $(COPY_FILE) --parents serialtool.ui .tmp/qtserial1.0.0/ && (cd `dirname .tmp/qtserial1.0.0` && $(TAR) qtserial1.0.0.tar qtserial1.0.0 && $(COMPRESS) qtserial1.0.0.tar) && $(MOVE) `dirname .tmp/qtserial1.0.0`/qtserial1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtserial1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_serialtool.cpp moc_readserial.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_serialtool.cpp moc_readserial.cpp
moc_serialtool.cpp: ui_serialtool.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h \
		readserial.h \
		serialtool.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) serialtool.h -o moc_serialtool.cpp

moc_readserial.cpp: qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h \
		readserial.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) readserial.h -o moc_readserial.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_serialtool.h
compiler_uic_clean:
	-$(DEL_FILE) ui_serialtool.h
ui_serialtool.h: serialtool.ui
	/usr/bin/uic-qt4 serialtool.ui -o ui_serialtool.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp serialtool.h \
		ui_serialtool.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h \
		readserial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

win_qextserialport.o: win_qextserialport.cpp win_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_qextserialport.o win_qextserialport.cpp

serialtool.o: serialtool.cpp serialtool.h \
		ui_serialtool.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h \
		readserial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialtool.o serialtool.cpp

readserial.o: readserial.cpp readserial.h \
		qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readserial.o readserial.cpp

qextserialport.o: qextserialport.cpp qextserialport.h \
		posix_qextserialport.h \
		qextserialbase.h \
		win_qextserialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o qextserialport.cpp

qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o qextserialbase.cpp

posix_qextserialport.o: posix_qextserialport.cpp posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o posix_qextserialport.cpp

moc_serialtool.o: moc_serialtool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialtool.o moc_serialtool.cpp

moc_readserial.o: moc_readserial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readserial.o moc_readserial.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

